name: Java CI with Maven for Microservices

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - { name: trainms, path: 'trainms/**' }
          - { name: bookingms, path: 'bookingms/**' }
          - { name: paymentms, path: 'paymentms/**' }
          - { name: userms, path: 'userms/**' }

    steps:
    - uses: actions/checkout@v4
    
    # Set up JDK 21
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    # Only run the job if the corresponding microservice directory has changes
    - name: Build and Test ${{ matrix.service.name }}
      if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }} && (github.event.push.changes || github.event.pull_request.changes) && contains(github.event.commits.*.modified, matrix.service.path)
      run: |
        cd ${{ matrix.service.name }}
        mvn -B package --file pom.xml
