name: Java CI with Maven for Microservices

on:
  push:
    branches:
      - "main"
    paths:
      - 'trainms/**'
      - 'bookingms/**'
      - 'paymentms/**'
      - 'userms/**'
  pull_request:
    branches:
      - "main"
    paths:
      - 'trainms/**'
      - 'bookingms/**'
      - 'paymentms/**'
      - 'userms/**'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [trainms, bookingms, paymentms, userms]

    steps:
    - uses: actions/checkout@v4

    # Set up JDK 21
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    # Conditional job running based on path changes
    - name: Build and Test ${{ matrix.service }}
      if: ${{ matrix.service == 'trainms' && (github.event_name == 'push' || github.event_name == 'pull_request') && (contains(github.event.head_commit.message, 'trainms') || github.event.pull_request.head.repo.default_branch == 'main') }}
      run: |
        cd ${{ matrix.service }}
        mvn -B package --file pom.xml
